
country_names = list("Switzerland" = "Switzerland",
                     "Iceland" = "Iceland",
                     "Denmark" = "Denmark",
                     "Norway" = "Norway",
                     "Canada" = "Canada",
                     "Finland" = "Finland",
                     "Netherlands" = "Netherlands",
                     "Sweden" = "Sweden",
                     "New Zealand" = "New Zealand",
                     "Australia" = "Australia",
                     "Israel" = "Israel",
                     "Costa Rica" = "Costa Rica",
                     "Austria" = "Austria",
                     "Mexico" = "Mexico",
                     "United States" = "United States",
                     "Brazil" = "Brazil",
                     "Luxembourg" = "Luxembourg",
                     "Ireland" = "Ireland",
                     "Belgium" = "Belgium",
                     "United Arab Emirates" = "United Arab Emirates",
                     "United Kingdom" = "United Kingdom",
                     "Oman" = "Oman",
                     "Venezuela" = "Venezuela",
                     "Singapore" = "Singapore",
                     "Panama" = "Panama",
                     "Germany" = "Germany",
                     "Chile" = "Chile",
                     "Qatar" = "Qatar",
                     "France" = "France",
                     "Argentina" = "Argentina",
                     "Czech Republic" = "Czech Republic",
                     "Uruguay" = "Uruguay",
                     "Colombia" = "Colombia",
                     "Thailand" = "Thailand",
                     "Saudi Arabia" = "Saudi Arabia",
                     "Spain" = "Spain",
                     "Malta" = "Malta",
                     "Taiwan" = "Taiwan",
                     "Kuwait" = "Kuwait",
                     "Suriname" = "Suriname",
                     "Trinidad and Tobago" = "Trinidad and Tobago",
                     "El Salvador" = "El Salvador",
                     "Guatemala" = "Guatemala",
                     "Uzbekistan" = "Uzbekistan",
                     "Slovakia" = "Slovakia",
                     "Japan" = "Japan",
                     "South Korea" = "South Korea",
                     "Ecuador" = "Ecuador",
                     "Bahrain" = "Bahrain",
                     "Italy" = "Italy",
                     "Bolivia" = "Bolivia",
                     "Moldova" = "Moldova",
                     "Paraguay" = "Paraguay",
                     "Kazakhstan" = "Kazakhstan",
                     "Slovenia" = "Slovenia",
                     "Lithuania" = "Lithuania",
                     "Nicaragua" = "Nicaragua",
                     "Peru" = "Peru",
                     "Belarus" = "Belarus",
                     "Poland" = "Poland",
                     "Malaysia" = "Malaysia",
                     "Croatia" = "Croatia",
                     "Libya" = "Libya",
                     "Russia" = "Russia",
                     "Jamaica" = "Jamaica",
                     "North Cyprus" = "North Cyprus",
                     "Cyprus" = "Cyprus",
                     "Algeria" = "Algeria",
                     "Kosovo" = "Kosovo",
                     "Turkmenistan" = "Turkmenistan",
                     "Mauritius" = "Mauritius",
                     "Hong Kong" = "Hong Kong",
                     "Estonia" = "Estonia",
                     "Indonesia" = "Indonesia",
                     "Vietnam" = "Vietnam",
                     "Turkey" = "Turkey",
                     "Kyrgyzstan" = "Kyrgyzstan",
                     "Nigeria" = "Nigeria",
                     "Bhutan" = "Bhutan",
                     "Azerbaijan" = "Azerbaijan",
                     "Pakistan" = "Pakistan",
                     "Jordan" = "Jordan",
                     "Montenegro" = "Montenegro",
                     "China" = "China",
                     "Zambia" = "Zambia",
                     "Romania" = "Romania",
                     "Serbia" = "Serbia",
                     "Portugal" = "Portugal",
                     "Latvia" = "Latvia",
                     "Philippines" = "Philippines",
                     "Somaliland region" = "Somaliland region",
                     "Morocco" = "Morocco",
                     "Macedonia" = "Macedonia",
                     "Mozambique" = "Mozambique",
                     "Albania" = "Albania",
                     "Bosnia and Herzegovina" = "Bosnia and Herzegovina",
                     "Lesotho" = "Lesotho",
                     "Dominican Republic" = "Dominican Republic",
                     "Laos" = "Laos",
                     "Mongolia" = "Mongolia",
                     "Swaziland" = "Swaziland",
                     "Greece" = "Greece",
                     "Lebanon" = "Lebanon",
                     "Hungary" = "Hungary",
                     "Honduras" = "Honduras",
                     "Tajikistan" = "Tajikistan",
                     "Tunisia" = "Tunisia",
                     "Palestinian Territories" = "Palestinian Territories",
                     "Bangladesh" = "Bangladesh",
                     "Iran" = "Iran",
                     "Ukraine" = "Ukraine",
                     "Iraq" = "Iraq",
                     "South Africa" = "South Africa",
                     "Ghana" = "Ghana",
                     "Zimbabwe" = "Zimbabwe",
                     "Liberia" = "Liberia",
                     "India" = "India",
                     "Sudan" = "Sudan",
                     "Haiti" = "Haiti",
                     "Congo (Kinshasa)" = "Congo (Kinshasa)",
                     "Nepal" = "Nepal",
                     "Ethiopia" = "Ethiopia",
                     "Sierra Leone" = "Sierra Leone",
                     "Mauritania" = "Mauritania",
                     "Kenya" = "Kenya",
                     "Djibouti" = "Djibouti",
                     "Armenia" = "Armenia",
                     "Botswana" = "Botswana",
                     "Myanmar" = "Myanmar",
                     "Georgia" = "Georgia",
                     "Malawi" = "Malawi",
                     "Sri Lanka" = "Sri Lanka",
                     "Cameroon" = "Cameroon",
                     "Bulgaria" = "Bulgaria",
                     "Egypt" = "Egypt",
                     "Yemen" = "Yemen",
                     "Angola" = "Angola",
                     "Mali" = "Mali",
                     "Congo (Brazzaville)" = "Congo (Brazzaville)",
                     "Comoros" = "Comoros",
                     "Uganda" = "Uganda",
                     "Senegal" = "Senegal",
                     "Gabon" = "Gabon",
                     "Niger" = "Niger",
                     "Cambodia" = "Cambodia",
                     "Tanzania" = "Tanzania",
                     "Madagascar" = "Madagascar",
                     "Central African Republic" = "Central African Republic",
                     "Chad" = "Chad",
                     "Guinea" = "Guinea",
                     "Ivory Coast" = "Ivory Coast",
                     "Burkina Faso" = "Burkina Faso",
                     "Afghanistan" = "Afghanistan",
                     "Rwanda" = "Rwanda",
                     "Benin" = "Benin",
                     "Syria" = "Syria",
                     "Burundi" = "Burundi",
                     "Togo" = "Togo")

data <- read.csv("../data/FullData.csv")
split = data %>% select(c('Country', 'HappinessScore', 'Year')) %>%
  group_split(Year) 

joined = merge(x=split[[1]], y=split[[2]], by='Country')
joined = merge(x=joined, y=split[[3]], by='Country')
joined = merge(x=joined, y=split[[4]], by='Country')
joined = merge(x=joined, y=split[[5]], by='Country')

colnames(joined)[2] <- "2015"
colnames(joined)[4] <- "2016"
colnames(joined)[6] <- "2017"
colnames(joined)[8] <- "2018"
colnames(joined)[10] <- "2019"
head(joined)
joined_data <- select(joined, c('Country', '2015', '2016', '2017', '2018', '2019'))
row.names(joined_data) <- joined_data$Country
joined_data <- subset(joined_data, select = -c(Country))

